export const actionTypes = {
  //  auth
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGIN_ERROR_MES_OVERALL: 'LOGIN_ERROR_MES_OVERALL',

  //  overall
  CHANGE_TOKEN: 'CHANGE_TOKEN',
  GET_ROLES: 'GET_ROLES',
  LOADED_APP_INACTIVE: 'LOADED_APP_INACTIVE',
  NETWORK_ACTIVE: 'NETWORK_ACTIVE',
  NETWORK_INACTIVE: 'NETWORK_INACTIVE',
  SET_ORG: 'SET_ORG',
  HEADER_CHANGE_TITLE: 'HEADER_CHANGE_TITLE',
  HEADER_CHANGE_NAVIGATION_BAR: 'HEADER_CHANGE_NAVIGATION_BAR',
  MQL: 'MQL',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  TOGGLE_MOBILE_SIDEBAR: 'TOGGLE_MOBILE_SIDEBAR',

  ABOUT_DIALOG_PREVIEW: 'ABOUT_DIALOG_PREVIEW',
  ALERT_DIALOG_PREVIEW: 'ALERT_DIALOG_PREVIEW',

  //  admin page
  ADMIN_PAGE_TABLE_SUCCESS: 'ADMIN_PAGE_TABLE_SUCCESS',
  ADMIN_PAGE_DIALOG_ADD: 'ADMIN_PAGE_DIALOG_ADD',
  ADMIN_PAGE_DIALOG_EDIT: 'ADMIN_PAGE_DIALOG_EDIT',

  //  hospitals
  HOSPITALS_PAGE_TABLE_SUCCESS: 'HOSPITALS_PAGE_TABLE_SUCCESS',
  HOSPITALS_PAGE_DIALOG_ADD: 'HOSPITALS_PAGE_DIALOG_ADD',
  HOSPITALS_PAGE_DIALOG_EDIT: 'HOSPITALS_PAGE_DIALOG_EDIT',

  // contacts
  EDIT_CONTACTS_DIALOG: 'EDIT_CONTACTS_DIALOG',
  GET_CONTACTS: 'GET_CONTACTS'
}
